In [1]:
import pandas as pd

In [2]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
df = pd.read_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/snic-departamentos-anual.csv", sep=";")

df.head()

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,codigo_delito_snic_id,cod_delito,codigo_delito_snic_nombre,cantidad_hechos,cantidad_victimas,cantidad_victimas_masc,cantidad_victimas_fem,cantidad_victimas_sd,tasa_hechos,tasa_victimas,tasa_victimas_masc,tasa_victimas_fem
0,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2000,1,1,Homicidios dolosos,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2000,10,10,Abusos sexuales con acceso carnal (violaciones),0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2000,11,11,Otros delitos contra la integridad sexual,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2000,12,12,Delitos contra el estado civil,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
4,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2000,13,13,Amenazas,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [7]:
sorted(df["codigo_delito_snic_nombre"].dropna().unique())

['Abuso sexual agravado',
 'Abuso sexual simple',
 'Abusos sexuales con acceso carnal (violaciones)',
 'Acceso ilegal a sistemas informáticos y daños informáticos',
 'Acopio y fabricación ilegal de armas piezas y municiones',
 'Amenazas',
 'Ciberdelitos sexuales vinculados a menores',
 'Comercialización y entrega de estupefacientes',
 'Confabulación de estupefacientes',
 'Contrabando Agravado',
 'Contrabando Simple',
 'Contrabando agravado',
 'Contrabando de elementos nucleares agresivos químicos armas y municiones',
 'Contrabando de estupefacientes',
 'Contrabando simple',
 'Contravenciones',
 'Daños (no incluye informáticos)',
 'Delitos contra el estado civil',
 'Delitos contra el honor',
 'Delitos contra el orden económico y financiero',
 'Delitos contra el orden público',
 'Delitos contra la administración pública',
 'Delitos contra la fe pública',
 'Delitos contra la seguridad de la nación',
 'Delitos contra la seguridad pública',
 'Delitos contra los poderes públicos y el orden constitucional',
 'Delitos migratorios',
 'Desvío de Importación de estupefacientes',
 'Entrega y comercialización ilegal de armas de fuego',
 'Estafas y defraudaciones (no incluye virtuales) y usura',
 'Estafas y defraudaciones asistidas virtualmente',
 'Extorsiones',
 'Fabricación adquisición transferencia y tenencia de explosivos y otros materiales peligrosos',
 'Homicidios culposos por otros hechos',
 'Homicidios dolosos',
 'Homicidios dolosos en grado de tentativa',
 'Hurtos',
 'Lesiones culposas en Accidentes Viales',
 'Lesiones culposas por otros hechos',
 'Lesiones dolosas',
 'Ley 23.737 (estupefacientes)',
 'Ley de fauna',
 'Ley de residuos peligrosos',
 'Muertes en accidentes viales',
 'Obstrucción del código aduanero',
 'Omisión adulteración y supresión de marcaje',
 'Organización y financiación de estupefacientes',
 'Otros delitos contra la integridad sexual',
 'Otros delitos contra la libertad',
 'Otros delitos contra la propiedad',
 'Otros delitos contra la seguridad pública',
 'Otros delitos contra las personas',
 'Otros delitos previstos en la ley 23.737',
 'Otros delitos previstos en leyes especiales',
 'Otros delitos previstos en leyes especiales n.c.p',
 'Portación ilegal de armas de fuego',
 'Robos (excluye los agravados por el resultado de lesiones y/o muertes)',
 'Robos agravados por el resultado de lesiones y/o muertes',
 'Robos agravados por el resultado de lesiones y/o muertes ',
 'Secuestros extorsivos',
 'Siembra y producción de estupefacientes',
 'Suicidios (consumados)',
 'Tenencia ilegal de armas de fuego',
 'Tenencia o entrega atenuada de estupefacientes',
 'Tenencia simple atenuada para uso personal de estupefacientes',
 'Tenencia simple de estupefacientes',
 'Tentativa de abuso sexual con acceso carnal',
 'Tentativas de hurto',
 'Tentativas de robo (excluye las agravadas por el res. de lesiones y/o muerte)',
 'Tentativas de robo agravado por el resultado de lesiones y/o muertes',
 'Trata de personas agravado',
 'Trata de personas simple']

In [8]:
for delito in sorted(df["codigo_delito_snic_nombre"].dropna().unique()):
    print(delito)

Abuso sexual agravado
Abuso sexual simple
Abusos sexuales con acceso carnal (violaciones)
Acceso ilegal a sistemas informáticos y daños informáticos
Acopio y fabricación ilegal de armas piezas y municiones
Amenazas
Ciberdelitos sexuales vinculados a menores
Comercialización y entrega de estupefacientes
Confabulación de estupefacientes
Contrabando Agravado
Contrabando Simple
Contrabando agravado
Contrabando de elementos nucleares agresivos químicos armas y municiones
Contrabando de estupefacientes
Contrabando simple
Contravenciones
Daños (no incluye informáticos)
Delitos contra el estado civil
Delitos contra el honor
Delitos contra el orden económico y financiero
Delitos contra el orden público
Delitos contra la administración pública
Delitos contra la fe pública
Delitos contra la seguridad de la nación
Delitos contra la seguridad pública
Delitos contra los poderes públicos y el orden constitucional
Delitos migratorios
Desvío de Importación de estupefacientes
Entrega y comercialización ilegal de armas de fuego
Estafas y defraudaciones (no incluye virtuales) y usura
Estafas y defraudaciones asistidas virtualmente
Extorsiones
Fabricación adquisición transferencia y tenencia de explosivos y otros materiales peligrosos
Homicidios culposos por otros hechos
Homicidios dolosos
Homicidios dolosos en grado de tentativa
Hurtos
Lesiones culposas en Accidentes Viales
Lesiones culposas por otros hechos
Lesiones dolosas
Ley 23.737 (estupefacientes)
Ley de fauna
Ley de residuos peligrosos
Muertes en accidentes viales
Obstrucción del código aduanero
Omisión adulteración y supresión de marcaje
Organización y financiación de estupefacientes
Otros delitos contra la integridad sexual
Otros delitos contra la libertad
Otros delitos contra la propiedad
Otros delitos contra la seguridad pública
Otros delitos contra las personas
Otros delitos previstos en la ley 23.737
Otros delitos previstos en leyes especiales
Otros delitos previstos en leyes especiales n.c.p
Portación ilegal de armas de fuego
Robos (excluye los agravados por el resultado de lesiones y/o muertes)
Robos agravados por el resultado de lesiones y/o muertes
Robos agravados por el resultado de lesiones y/o muertes
Secuestros extorsivos
Siembra y producción de estupefacientes
Suicidios (consumados)
Tenencia ilegal de armas de fuego
Tenencia o entrega atenuada de estupefacientes
Tenencia simple atenuada para uso personal de estupefacientes
Tenencia simple de estupefacientes
Tentativa de abuso sexual con acceso carnal
Tentativas de hurto
Tentativas de robo (excluye las agravadas por el res. de lesiones y/o muerte)
Tentativas de robo agravado por el resultado de lesiones y/o muertes
Trata de personas agravado
Trata de personas simple

In [9]:
delitos_propiedad_lista = [
    "Hurtos",
    "Tentativas de hurto",
    "Robos (excluye los agravados por el resultado de lesiones y/o muertes)",
    "Robos agravados por el resultado de lesiones y/o muertes",
    "Tentativas de robo (excluye las agravadas por el res. de lesiones y/o muerte)",
    "Tentativas de robo agravado por el resultado de lesiones y/o muertes",
    "Daños (no incluye informáticos)",
    "Otros delitos contra la propiedad",
    "Estafas y defraudaciones (no incluye virtuales) y usura",
    "Estafas y defraudaciones asistidas virtualmente",
    "Extorsiones"
]

In [10]:
df_propiedad = df[
    df["codigo_delito_snic_nombre"].isin(delitos_propiedad_lista)
]

In [11]:
df_propiedad["codigo_delito_snic_nombre"].unique()

array(['Robos (excluye los agravados por el resultado de lesiones y/o muertes)',
       'Tentativas de robo (excluye las agravadas por el res. de lesiones y/o muerte)',
       'Tentativas de robo agravado por el resultado de lesiones y/o muertes',
       'Hurtos', 'Tentativas de hurto',
       'Otros delitos contra la propiedad',
       'Robos agravados por el resultado de lesiones y/o muertes',
       'Extorsiones',
       'Estafas y defraudaciones (no incluye virtuales) y usura',
       'Estafas y defraudaciones asistidas virtualmente',
       'Daños (no incluye informáticos)'], dtype=object)

In [12]:
df_agg = df_propiedad.groupby(
    [
        "provincia_id",
        "provincia_nombre",
        "departamento_id",
        "departamento_nombre",
        "anio"
    ]
).agg({
    "cantidad_hechos": "sum",
    "cantidad_victimas": "sum"
}).reset_index()

In [13]:
df_agg = df_agg.rename(columns={
    "cantidad_hechos": "delitos_propiedad_hechos",
    "cantidad_victimas": "delitos_propiedad_victimas"
})

In [14]:
df_agg.head(50)

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,delitos_propiedad_hechos,delitos_propiedad_victimas
0,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2000,0,0.0
1,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2001,0,0.0
2,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2002,0,0.0
3,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2003,0,0.0
4,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2004,0,0.0
5,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2005,0,0.0
6,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2006,0,0.0
7,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2007,0,0.0
8,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2008,0,0.0
9,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2009,0,0.0
10,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2010,0,0.0
11,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2011,0,0.0
12,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2012,0,0.0
13,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2013,0,0.0
14,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2014,0,0.0
15,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2015,0,0.0
16,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2016,0,0.0
17,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2017,17609,0.0
18,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2018,18374,0.0
19,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2019,21721,0.0
20,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2020,9773,0.0
21,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2021,13012,0.0
22,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2022,20959,0.0
23,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2023,23541,0.0
24,2,Ciudad Autónoma de Buenos Aires,2001,Comuna 1,2024,24297,0.0
25,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2000,0,0.0
26,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2001,0,0.0
27,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2002,0,0.0
28,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2003,0,0.0
29,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2004,0,0.0
30,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2005,0,0.0
31,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2006,0,0.0
32,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2007,0,0.0
33,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2008,0,0.0
34,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2009,0,0.0
35,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2010,0,0.0
36,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2011,0,0.0
37,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2012,0,0.0
38,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2013,0,0.0
39,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2014,0,0.0
40,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2015,0,0.0
41,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2016,0,0.0
42,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2017,5747,0.0
43,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2018,6514,0.0
44,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2019,7062,0.0
45,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2020,3801,0.0
46,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2021,6055,0.0
47,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2022,7858,0.0
48,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2023,8690,0.0
49,2,Ciudad Autónoma de Buenos Aires,2002,Comuna 2,2024,8829,0.0

In [15]:
df_agg.duplicated(
    subset=["departamento_id", "anio"]
).sum()

np.int64(0)

In [16]:
df_agg.shape

(13342, 7)

In [17]:
df_agg["anio"].nunique()

25

In [18]:

df_agg["departamento_id"].nunique()

555

In [19]:
df_agg.to_csv(r"/content/drive/MyDrive/Practica_Profesionalizante_3/Copia_pre_proyecto/data/raw/snic-departamentos-anual.csv",
    index=False
)

In [20]:
df_agg.isnull().sum()

provincia_id                  0
provincia_nombre              0
departamento_id               0
departamento_nombre           0
anio                          0
delitos_propiedad_hechos      0
delitos_propiedad_victimas    0
dtype: int64

In [21]:
(df_agg["delitos_propiedad_hechos"] == 0).sum()

np.int64(997)

In [22]:
df_agg.describe()

,provincia_id,departamento_id,anio,delitos_propiedad_hechos,delitos_propiedad_victimas
count,13342.000000,13342.000000,13342.000000,13342.000000,13342.0
mean,36.766602,36971.613027,2012.048493,1553.557638,0.0
std,29.303392,29220.931734,7.229362,6637.869425,0.0
min,2.000000,2001.000000,2000.000000,0.000000,0.0
25%,6.000000,6763.000000,2006.000000,68.000000,0.0
50%,30.000000,30028.000000,2012.000000,230.000000,0.0
75%,62.000000,62084.000000,2018.000000,902.750000,0.0
max,94.000000,94999.000000,2024.000000,156930.000000,0.0

In [23]:
df_agg = df_agg.drop(columns=["delitos_propiedad_victimas"])

In [24]:
df_agg.sort_values("delitos_propiedad_hechos", ascending=False).head(10)

,provincia_id,provincia_nombre,departamento_id,departamento_nombre,anio,delitos_propiedad_hechos
383,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2008,156930
384,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2009,153227
382,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2007,151027
385,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2010,148926
386,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2011,148184
381,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2006,146382
387,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2012,146337
377,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2002,144676
375,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2000,143806
376,2,Ciudad Autónoma de Buenos Aires,2999,Departamento sin determinar,2001,142611

In [25]:
import plotly.express as px

df_year = df_agg.groupby("anio", as_index=False)["delitos_propiedad_hechos"].sum()
fig = px.line(
    df_year,
    x="anio",
    y="delitos_propiedad_hechos",
    title="Evolución de delitos contra la propiedad",
    labels={"anio": "Año", "delitos_propiedad_hechos": "Hechos"},
    template="plotly_dark"
)
fig.show()